/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package book;

import java.awt.Image;
import javax.swing.ImageIcon;


public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public static int book_id;
    
    public home() {
        initComponents();
        setSession();
        getRec();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSessionId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnadventure = new javax.swing.JButton();
        btnhorror = new javax.swing.JButton();
        btnbiography = new javax.swing.JButton();
        btnthriller = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 750));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 13, 74, 35);

        lblSessionId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSessionId.setForeground(new java.awt.Color(255, 255, 255));
        lblSessionId.setText("user");
        getContentPane().add(lblSessionId);
        lblSessionId.setBounds(492, 13, 150, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("BOOK STORE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 0, 255, 102);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT A BOOK GENRE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(277, 109, 251, 64);

        btnadventure.setBackground(new java.awt.Color(255, 255, 255));
        btnadventure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadventure.setText("ADVENTURE");
        btnadventure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadventureActionPerformed(evt);
            }
        });
        getContentPane().add(btnadventure);
        btnadventure.setBounds(290, 280, 187, 60);

        btnhorror.setBackground(new java.awt.Color(255, 255, 255));
        btnhorror.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhorror.setText("HORROR");
        btnhorror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhorrorActionPerformed(evt);
            }
        });
        getContentPane().add(btnhorror);
        btnhorror.setBounds(292, 201, 187, 60);

        btnbiography.setBackground(new java.awt.Color(255, 255, 255));
        btnbiography.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnbiography.setText("BIOGRAPHY");
        btnbiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbiographyActionPerformed(evt);
            }
        });
        getContentPane().add(btnbiography);
        btnbiography.setBounds(290, 360, 187, 60);

        btnthriller.setBackground(new java.awt.Color(255, 255, 255));
        btnthriller.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnthriller.setText("THRILLER");
        btnthriller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthrillerActionPerformed(evt);
            }
        });
        getContentPane().add(btnthriller);
        btnthriller.setBounds(290, 440, 187, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("LOGOUT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 20, 106, 44);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("RECOMMENDED BOOKS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 560, 369, 61);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 850, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadventureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadventureActionPerformed
        this.setVisible(false);
        new adventure().setVisible(true);
    }//GEN-LAST:event_btnadventureActionPerformed

    private void btnthrillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthrillerActionPerformed
        this.setVisible(false);
        new thriller().setVisible(true);
    }//GEN-LAST:event_btnthrillerActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnhorrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhorrorActionPerformed
        this.setVisible(false);
        new horror().setVisible(true);
    }//GEN-LAST:event_btnhorrorActionPerformed

    private void btnbiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbiographyActionPerformed
        this.setVisible(false);
        new biography().setVisible(true);
    }//GEN-LAST:event_btnbiographyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new recommended_books().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadventure;
    private javax.swing.JButton btnbiography;
    private javax.swing.JButton btnhorror;
    private javax.swing.JButton btnthriller;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblSessionId;
    // End of variables declaration//GEN-END:variables

    private void setSession() {
        lblSessionId.setText(login.user_name);        
        
    }

    private void getRec() {

    }
}
