/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book;

import com.datastax.driver.core.ResultSet;
import com.datastax.driver.core.Row;
import com.datastax.driver.core.Session;
import java.io.File;
import java.util.Iterator;
import java.util.List;
import org.apache.mahout.cf.taste.impl.model.file.FileDataModel;
import org.apache.mahout.cf.taste.impl.neighborhood.NearestNUserNeighborhood;
import org.apache.mahout.cf.taste.impl.recommender.GenericUserBasedRecommender;
import org.apache.mahout.cf.taste.impl.similarity.PearsonCorrelationSimilarity;
import org.apache.mahout.cf.taste.model.DataModel;
import org.apache.mahout.cf.taste.neighborhood.UserNeighborhood;
import org.apache.mahout.cf.taste.recommender.RecommendedItem;
import org.apache.mahout.cf.taste.recommender.Recommender;
import org.apache.mahout.cf.taste.similarity.UserSimilarity;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
        
public class recommended_books extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public recommended_books() {
        initComponents();
        getDetails();
        getRecommendedBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 750));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("BOOK STORE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 286, 85);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(155, 330, 0, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HOME");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 20, 58, 43);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hello,");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 180, 49, 52);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("As per your interests, we are recommending these books. ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 460, 47);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 180, 170, 52);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 140, 320, 190);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hope you like them...");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 290, 169, 22);

        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(205, 315));
        jLabel8.setMinimumSize(new java.awt.Dimension(205, 315));
        jLabel8.setPreferredSize(new java.awt.Dimension(205, 315));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 390, 200, 300);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 390, 200, 300);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 390, 200, 300);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(640, 390, 200, 300);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 850, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked


        private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {                                     
        home.book_id = Integer.parseInt(jLabel8.getToolTipText());
        this.setVisible(false);
        new rate().setVisible(true);    }                                    

         private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {                                     
        home.book_id = Integer.parseInt(jLabel9.getToolTipText());
        this.setVisible(false);
        new rate().setVisible(true);    }                                    

         private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {                                     
        home.book_id = Integer.parseInt(jLabel10.getToolTipText());
        this.setVisible(false);
        new rate().setVisible(true);    }                                    
        
         private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        home.book_id = Integer.parseInt(jLabel11.getToolTipText());
        this.setVisible(false);
        new rate().setVisible(true);    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recommended_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recommended_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recommended_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recommended_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recommended_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void getDetails() {
        jLabel3.setText(Integer.toString(login.session_id));
        jLabel7.setText(login.user_name);
    }

    private void getRecommendedBook() {
        try{
        DataModel model = new FileDataModel(new File("data.csv"));
        UserSimilarity similarity = new PearsonCorrelationSimilarity(model);
        UserNeighborhood neighborhood = new NearestNUserNeighborhood(5, similarity, model);
        Recommender recommender = new GenericUserBasedRecommender(model, neighborhood, similarity);

        List<RecommendedItem> recommendations = recommender.recommend(login.session_id, 4);
        
        Session recSession=new Book().CassandraHelper();
             int count=1;
            
            X:for (RecommendedItem recommendation : recommendations) {
            System.out.println(recommendation);
            //jTextArea1.setText("\t"+jTextArea1.getText()+"\n"+recommendation);
            //jTextArea1.setText("\t"+jTextArea1.getText()+"\n Book Id :"+Integer.toString((int) recommendation.getItemID()));
            String Query="SELECT * FROM book_details";
            ResultSet rs = recSession.execute(Query);
            Iterator<Row> rows=rs.iterator();
           
            
            while(rows.hasNext())
            {
               Row o=rows.next();
               if(o.getInt("book_id")==recommendation.getItemID())
               {  
                jTextArea1.setText("\t"+jTextArea1.getText()+"\n\tBook Id :"+Integer.toString((int) recommendation.getItemID())+"\t"+o.getString("book_name")+"  ("+o.getString("genre")+")");
                //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+Integer.toString((int) recommendation.getItemID())+".jpg"))); // NOI18N
                      
                     if(count==1)
                       {
                           jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+Integer.toString((int) recommendation.getItemID())+".jpg"))); 
                           jLabel8.setToolTipText(Integer.toString((int) recommendation.getItemID())); 
                          count++;
                       }
                       else if(count==2)
                       {
                            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+Integer.toString((int) recommendation.getItemID())+".jpg")));  
                            jLabel9.setToolTipText(Integer.toString((int) recommendation.getItemID())); 
                            count++;
                       }
                       else if(count==3)
                       {
                           jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+Integer.toString((int) recommendation.getItemID())+".jpg")));
                           jLabel10.setToolTipText(Integer.toString((int) recommendation.getItemID())); 
                           count++;
                       }
                       else if(count==4)
                       {
                            jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+Integer.toString((int) recommendation.getItemID())+".jpg")));
                            jLabel11.setToolTipText(Integer.toString((int) recommendation.getItemID())); 
                            count++;
                       }
                     else
                       {
                           count++;
                       }
               }
               
            }       
        }
            count++;
        }
        catch(Exception e)
        {
            e.getMessage();
        }

    }
}
